/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.RepairJobs;
import Controller.RepairJobsController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pamud
 */
public class AllocateEmployee extends javax.swing.JFrame {

    RepairJobs rob;
    RepairJobsController rcob;
    
    public AllocateEmployee() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        tfEmpID.setBackground(new java.awt.Color(0,0,0,1));
        tfInvoiceId.setBackground(new java.awt.Color(0,0,0,1));
        tfReturnDate.setBackground(new java.awt.Color(0,0,0,1));
        tfDescription.setBackground(new java.awt.Color(0,0,0,1));
        tfTaskID.setBackground(new java.awt.Color(0,0,0,1));
        
        rcob = new RepairJobsController();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTaskID = new javax.swing.JTextField();
        tfEmpID = new javax.swing.JTextField();
        tfInvoiceId = new javax.swing.JTextField();
        tfReturnDate = new javax.swing.JTextField();
        tfDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("View In Table");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 540, 130, 30);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Allocate Employees to the repairs ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 40, 550, 30);

        tfTaskID.setBackground(new java.awt.Color(0, 0, 0));
        tfTaskID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfTaskID.setForeground(new java.awt.Color(255, 255, 255));
        tfTaskID.setText("Task ID");
        tfTaskID.setBorder(null);
        tfTaskID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTaskIDMouseClicked(evt);
            }
        });
        tfTaskID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaskIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfTaskID);
        tfTaskID.setBounds(380, 140, 410, 30);

        tfEmpID.setBackground(new java.awt.Color(51, 51, 51));
        tfEmpID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfEmpID.setForeground(new java.awt.Color(255, 255, 255));
        tfEmpID.setText("Employee ID");
        tfEmpID.setBorder(null);
        tfEmpID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEmpIDMouseClicked(evt);
            }
        });
        tfEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmpIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmpID);
        tfEmpID.setBounds(380, 220, 420, 30);

        tfInvoiceId.setBackground(new java.awt.Color(0, 0, 0));
        tfInvoiceId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfInvoiceId.setForeground(new java.awt.Color(255, 255, 255));
        tfInvoiceId.setText("Invoice ID");
        tfInvoiceId.setBorder(null);
        tfInvoiceId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfInvoiceIdMouseClicked(evt);
            }
        });
        tfInvoiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInvoiceIdActionPerformed(evt);
            }
        });
        getContentPane().add(tfInvoiceId);
        tfInvoiceId.setBounds(380, 310, 420, 27);

        tfReturnDate.setBackground(new java.awt.Color(0, 0, 0));
        tfReturnDate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfReturnDate.setForeground(new java.awt.Color(255, 255, 255));
        tfReturnDate.setText("Description");
        tfReturnDate.setBorder(null);
        tfReturnDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfReturnDateMouseClicked(evt);
            }
        });
        getContentPane().add(tfReturnDate);
        tfReturnDate.setBounds(380, 480, 420, 27);

        tfDescription.setBackground(new java.awt.Color(0, 0, 0));
        tfDescription.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfDescription.setForeground(new java.awt.Color(255, 255, 255));
        tfDescription.setText("Return Date");
        tfDescription.setBorder(null);
        tfDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDescriptionMouseClicked(evt);
            }
        });
        getContentPane().add(tfDescription);
        tfDescription.setBounds(380, 400, 420, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/AllocateEmployee.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -160, 2050, 1050);

        btnBack.setText("jButton1");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(240, 600, 150, 40);

        btnAdd.setText("jButton2");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(445, 602, 150, 40);

        btnUpdate.setText("jButton3");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(660, 610, 150, 30);

        btnRemove.setText("jButton4");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(870, 602, 160, 40);

        btnTable.setBackground(new java.awt.Color(102, 0, 153));
        btnTable.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTable.setForeground(new java.awt.Color(255, 255, 255));
        btnTable.setText("View In Table");
        btnTable.setBorder(null);
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableActionPerformed(evt);
            }
        });
        getContentPane().add(btnTable);
        btnTable.setBounds(660, 540, 160, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfInvoiceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInvoiceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInvoiceIdActionPerformed

    private void tfEmpIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEmpIDMouseClicked
        tfEmpID.setText(null);
    }//GEN-LAST:event_tfEmpIDMouseClicked

    private void tfInvoiceIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfInvoiceIdMouseClicked
        tfInvoiceId.setText(null);
    }//GEN-LAST:event_tfInvoiceIdMouseClicked

    private void tfDescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDescriptionMouseClicked
        tfDescription.setText(null);
    }//GEN-LAST:event_tfDescriptionMouseClicked

    private void tfReturnDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfReturnDateMouseClicked
        tfReturnDate.setText(null);
    }//GEN-LAST:event_tfReturnDateMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        String TaskID = tfTaskID.getText();
        String EmpID = tfEmpID.getText();
        String InvoiceID = tfInvoiceId.getText();
        String ReturnDate = tfReturnDate.getText();
        String Description =  tfDescription.getText(); 

        rob = rcob.AddRepairJobs(TaskID, EmpID, InvoiceID, TaskID, Description);
        boolean result = rcob.AddtoDB(rob);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully added to the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "Adding to the databse unsuccessfull","Error",0 );
        }
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        String TaskID = tfTaskID.getText();
        String EmpID = tfEmpID.getText();
        String InvoiceID = tfInvoiceId.getText();
        String ReturnDate = tfReturnDate.getText();
        String Description =  tfDescription.getText();
        
        boolean result = rcob.UpdateDB(TaskID, EmpID, InvoiceID, ReturnDate, Description);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully updated the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "updating the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String TaskID = tfTaskID.getText();
        
        tfEmpID.setText(null);
        tfInvoiceId.setText(null);
        tfReturnDate.setText(null);
        tfDescription.setText(null);
        
        boolean result = rcob.DeleteDB(TaskID);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully deleted from the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "deleting from the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmpIDActionPerformed

    private void tfTaskIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaskIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTaskIDActionPerformed

    private void tfTaskIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTaskIDMouseClicked
         tfTaskID.setText(null);
    }//GEN-LAST:event_tfTaskIDMouseClicked

    private void btnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllocateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnTable;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfEmpID;
    private javax.swing.JTextField tfInvoiceId;
    private javax.swing.JTextField tfReturnDate;
    private javax.swing.JTextField tfTaskID;
    // End of variables declaration//GEN-END:variables
}
