/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.JFrame;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Pamud
 */
public class DashboardDark extends javax.swing.JFrame {

    ResultSet rs;
    DBconnector dbc;
    
    public DashboardDark() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        pnlSideMenu.setVisible(false);
        dbc = DBconnector.getSingleInstance();
        
        try {
            int totQuantity = 0;
            int total = 0;
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetickerdb","root","");
            Statement stmt = conn.createStatement();
            String sql = "Select * from invoices";
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()){

                int quantity = Integer.parseInt(rs.getString("Quantity")) ;
                int price = Integer.parseInt(rs.getString("UnitPrice")) ;
                int pay = quantity*price;
                total = pay+total;
                totQuantity = totQuantity + quantity;
                
                
                tfWatchCount.setText(Integer.toString(totQuantity));
                lblTotal.setText("RS."+Integer.toString(total));
            }
            
            
        } catch (Exception e) {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlSideMenu = new javax.swing.JPanel();
        btnSun = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JLabel();
        btnManageInvoice = new javax.swing.JLabel();
        btnRepJobs = new javax.swing.JLabel();
        btnSpareParts = new javax.swing.JLabel();
        btnPartSup = new javax.swing.JLabel();
        btnWatch = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        lblSideMenu = new javax.swing.JLabel();
        HideMenu = new javax.swing.JLabel();
        btnNewPurchse = new javax.swing.JLabel();
        btnRepairJobs = new javax.swing.JLabel();
        btnUpdateStock = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfWatchCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnTotalWatches = new javax.swing.JLabel();
        MenuIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfWatchCount1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        pnlSideMenu.setLayout(null);

        btnSun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/sun.png"))); // NOI18N
        btnSun.setText("jLabel2");
        btnSun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSunMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnSun);
        btnSun.setBounds(210, 10, 30, 30);

        Logo.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setText("Time Ticker");
        pnlSideMenu.add(Logo);
        Logo.setBounds(60, 90, 140, 30);

        btnCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setText("Customer");
        btnCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCustomerMouseMoved(evt);
            }
        });
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnCustomer);
        btnCustomer.setBounds(90, 170, 110, 27);

        btnManageInvoice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManageInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btnManageInvoice.setText("Manage Invoice");
        btnManageInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageInvoice.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnManageInvoiceMouseMoved(evt);
            }
        });
        btnManageInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageInvoiceMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnManageInvoice);
        btnManageInvoice.setBounds(90, 240, 150, 27);

        btnRepJobs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRepJobs.setForeground(new java.awt.Color(255, 255, 255));
        btnRepJobs.setText("Repairing Jobs");
        btnRepJobs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepJobs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRepJobsMouseMoved(evt);
            }
        });
        btnRepJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRepJobsMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnRepJobs);
        btnRepJobs.setBounds(90, 310, 130, 27);

        btnSpareParts.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSpareParts.setForeground(new java.awt.Color(255, 255, 255));
        btnSpareParts.setText("Spare Parts");
        btnSpareParts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSpareParts.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSparePartsMouseMoved(evt);
            }
        });
        btnSpareParts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSparePartsMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnSpareParts);
        btnSpareParts.setBounds(90, 380, 110, 27);

        btnPartSup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPartSup.setForeground(new java.awt.Color(255, 255, 255));
        btnPartSup.setText("Part Suppliers");
        btnPartSup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPartSup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPartSupMouseMoved(evt);
            }
        });
        btnPartSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPartSupMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnPartSup);
        btnPartSup.setBounds(90, 450, 120, 27);

        btnWatch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnWatch.setForeground(new java.awt.Color(255, 255, 255));
        btnWatch.setText("Watch");
        btnWatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWatch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnWatchMouseMoved(evt);
            }
        });
        btnWatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWatchMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnWatch);
        btnWatch.setBounds(90, 510, 110, 27);

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLogOutMouseMoved(evt);
            }
        });
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        pnlSideMenu.add(btnLogOut);
        btnLogOut.setBounds(70, 660, 80, 25);

        lblSideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/SideMenu.jpg"))); // NOI18N
        lblSideMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSideMenuMouseMoved(evt);
            }
        });
        pnlSideMenu.add(lblSideMenu);
        lblSideMenu.setBounds(0, 0, 252, 720);

        getContentPane().add(pnlSideMenu);
        pnlSideMenu.setBounds(0, 0, 250, 720);

        HideMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HideMenuMouseMoved(evt);
            }
        });
        getContentPane().add(HideMenu);
        HideMenu.setBounds(250, 0, 30, 720);

        btnNewPurchse.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnNewPurchse.setForeground(new java.awt.Color(255, 255, 255));
        btnNewPurchse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNewPurchse.setText("New Purchase");
        btnNewPurchse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewPurchse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNewPurchseMouseMoved(evt);
            }
        });
        btnNewPurchse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewPurchseMouseClicked(evt);
            }
        });
        getContentPane().add(btnNewPurchse);
        btnNewPurchse.setBounds(110, 560, 150, 21);

        btnRepairJobs.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnRepairJobs.setForeground(new java.awt.Color(255, 255, 255));
        btnRepairJobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRepairJobs.setText("Repair Jobs");
        btnRepairJobs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepairJobs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRepairJobsMouseMoved(evt);
            }
        });
        btnRepairJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRepairJobsMouseClicked(evt);
            }
        });
        getContentPane().add(btnRepairJobs);
        btnRepairJobs.setBounds(420, 560, 150, 21);

        btnUpdateStock.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnUpdateStock.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdateStock.setText("Employee Chart");
        btnUpdateStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateStock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUpdateStockMouseMoved(evt);
            }
        });
        btnUpdateStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateStockMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdateStock);
        btnUpdateStock.setBounds(720, 560, 150, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 20, 100, 27);

        tfWatchCount.setFont(new java.awt.Font("Digital-7", 0, 40)); // NOI18N
        tfWatchCount.setForeground(new java.awt.Color(255, 255, 255));
        tfWatchCount.setText("0021");
        getContentPane().add(tfWatchCount);
        tfWatchCount.setBounds(760, 220, 90, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Watches");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(740, 200, 110, 19);

        tfUserName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tfUserName.setForeground(new java.awt.Color(255, 255, 255));
        tfUserName.setText("Employee");
        getContentPane().add(tfUserName);
        tfUserName.setBounds(190, 26, 110, 20);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Today's Sales");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 160, 220, 29);

        lblTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("RS 0040360");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(110, 210, 210, 50);
        getContentPane().add(btnTotalWatches);
        btnTotalWatches.setBounds(690, 130, 200, 240);

        MenuIcon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MenuIconMouseMoved(evt);
            }
        });
        getContentPane().add(MenuIcon);
        MenuIcon.setBounds(10, 10, 40, 50);

        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/DashboardDark.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1321, 720);

        tfWatchCount1.setFont(new java.awt.Font("Digital-7", 0, 40)); // NOI18N
        tfWatchCount1.setForeground(new java.awt.Color(255, 255, 255));
        tfWatchCount1.setText("6429");
        getContentPane().add(tfWatchCount1);
        tfWatchCount1.setBounds(750, 220, 90, 50);

        jLabel16.setText("300 Watches");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1100, 180, 80, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuIconMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuIconMouseMoved
        pnlSideMenu.setVisible(true);
    }//GEN-LAST:event_MenuIconMouseMoved

    private void HideMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMenuMouseMoved
        pnlSideMenu.setVisible(false);
    }//GEN-LAST:event_HideMenuMouseMoved

    private void btnCustomerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseMoved
        btnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_btnCustomerMouseMoved

    private void lblSideMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSideMenuMouseMoved
        btnCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnManageInvoice.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnRepJobs.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnSpareParts.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnPartSup.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnWatch.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18));
        
        
    }//GEN-LAST:event_lblSideMenuMouseMoved

    private void btnManageInvoiceMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageInvoiceMouseMoved
        btnManageInvoice.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_btnManageInvoiceMouseMoved

    private void btnRepJobsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepJobsMouseMoved
        btnRepJobs.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_btnRepJobsMouseMoved

    private void btnSparePartsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSparePartsMouseMoved
        btnSpareParts.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_btnSparePartsMouseMoved

    private void btnPartSupMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartSupMouseMoved
        btnPartSup.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_btnPartSupMouseMoved

    private void btnWatchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWatchMouseMoved
        btnWatch.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_btnWatchMouseMoved

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        RegNewCustomer mi1 = new RegNewCustomer();
        mi1.show();
        dispose();
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnManageInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageInvoiceMouseClicked
        ManageSalesInvoice mi1 = new ManageSalesInvoice();
        mi1.show();
        dispose();
    }//GEN-LAST:event_btnManageInvoiceMouseClicked

    private void btnRepJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepJobsMouseClicked
        AllocateEmployee ae1 = new AllocateEmployee();
        ae1.show();
        dispose();
    }//GEN-LAST:event_btnRepJobsMouseClicked

    private void btnPartSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartSupMouseClicked
        ManagePartSup mp1 = new ManagePartSup();
        mp1.show();
        dispose();
    }//GEN-LAST:event_btnPartSupMouseClicked

    private void btnLogOutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseMoved
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_btnLogOutMouseMoved

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        Login l1 = new Login();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnSparePartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSparePartsMouseClicked
        ManageStock l1 = new ManageStock();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnSparePartsMouseClicked

    private void btnSunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSunMouseClicked
        Dashboard l1 = new Dashboard();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnSunMouseClicked

    private void btnNewPurchseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewPurchseMouseMoved
        btnNewPurchse.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
    }//GEN-LAST:event_btnNewPurchseMouseMoved

    private void btnUpdateStockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateStockMouseMoved
        btnUpdateStock.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
    }//GEN-LAST:event_btnUpdateStockMouseMoved

    private void btnRepairJobsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepairJobsMouseMoved
        btnRepairJobs.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
    }//GEN-LAST:event_btnRepairJobsMouseMoved

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
       btnNewPurchse.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
       btnUpdateStock.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
       btnRepairJobs.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
    }//GEN-LAST:event_jLabel5MouseMoved

    private void btnNewPurchseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewPurchseMouseClicked
        ManageSalesInvoice l1 = new ManageSalesInvoice();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnNewPurchseMouseClicked

    private void btnRepairJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepairJobsMouseClicked
        AllocateEmployee l1 = new AllocateEmployee();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnRepairJobsMouseClicked

    private void btnUpdateStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateStockMouseClicked
        TableEmployee l1 = new TableEmployee();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnUpdateStockMouseClicked

    private void btnWatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWatchMouseClicked
        ManageWatch l1 = new ManageWatch();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnWatchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardDark().setVisible(true);
                //rs = dbc.ShowExecuteQuary("Select ")
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HideMenu;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MenuIcon;
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnManageInvoice;
    private javax.swing.JLabel btnNewPurchse;
    private javax.swing.JLabel btnPartSup;
    private javax.swing.JLabel btnRepJobs;
    private javax.swing.JLabel btnRepairJobs;
    private javax.swing.JLabel btnSpareParts;
    private javax.swing.JLabel btnSun;
    private javax.swing.JLabel btnTotalWatches;
    private javax.swing.JLabel btnUpdateStock;
    private javax.swing.JLabel btnWatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblSideMenu;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlSideMenu;
    private javax.swing.JLabel tfUserName;
    private javax.swing.JLabel tfWatchCount;
    private javax.swing.JLabel tfWatchCount1;
    // End of variables declaration//GEN-END:variables
}
