/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.SalesInvoice;
import Controller.SalesInvoiceController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.JFrame;

/**
 *
 * @author Pamud
 */
public class ManageSalesInvoice extends javax.swing.JFrame {

    SalesInvoice sob;
    SalesInvoiceController scob;
    
    int a;
    int b;
    
    
    
    public ManageSalesInvoice() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        tfCustomerID.setBackground(new java.awt.Color(0,0,0,1));
        tfWatchID.setBackground(new java.awt.Color(0,0,0,1));
        tfQuantity.setBackground(new java.awt.Color(0,0,0,1));
        tfUnitPrice.setBackground(new java.awt.Color(0,0,0,1));
        tfInvoiceID.setBackground(new java.awt.Color(0,0,0,1));
        
        scob = new SalesInvoiceController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfInvoiceID = new javax.swing.JTextField();
        tfCustomerID = new javax.swing.JTextField();
        tfWatchID = new javax.swing.JTextField();
        tfUnitPrice = new javax.swing.JTextField();
        tfQuantity = new javax.swing.JTextField();
        jlBL = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Invoice");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 40, 270, 50);

        tfInvoiceID.setBackground(new java.awt.Color(0, 0, 0));
        tfInvoiceID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfInvoiceID.setForeground(new java.awt.Color(255, 255, 255));
        tfInvoiceID.setText("Invoice ID");
        tfInvoiceID.setBorder(null);
        tfInvoiceID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfInvoiceIDMouseClicked(evt);
            }
        });
        getContentPane().add(tfInvoiceID);
        tfInvoiceID.setBounds(360, 140, 210, 30);

        tfCustomerID.setBackground(new java.awt.Color(51, 51, 51));
        tfCustomerID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfCustomerID.setForeground(new java.awt.Color(255, 255, 255));
        tfCustomerID.setText("Customer ID");
        tfCustomerID.setBorder(null);
        tfCustomerID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfCustomerIDMouseClicked(evt);
            }
        });
        getContentPane().add(tfCustomerID);
        tfCustomerID.setBounds(360, 210, 210, 27);

        tfWatchID.setBackground(new java.awt.Color(51, 51, 51));
        tfWatchID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfWatchID.setForeground(new java.awt.Color(255, 255, 255));
        tfWatchID.setText("Watch ID");
        tfWatchID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfWatchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfWatchIDMouseClicked(evt);
            }
        });
        getContentPane().add(tfWatchID);
        tfWatchID.setBounds(360, 290, 210, 31);

        tfUnitPrice.setBackground(new java.awt.Color(51, 51, 51));
        tfUnitPrice.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfUnitPrice.setForeground(new java.awt.Color(255, 255, 255));
        tfUnitPrice.setText("Unit Price");
        tfUnitPrice.setBorder(null);
        tfUnitPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUnitPriceMouseClicked(evt);
            }
        });
        tfUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnitPriceActionPerformed(evt);
            }
        });
        getContentPane().add(tfUnitPrice);
        tfUnitPrice.setBounds(360, 370, 210, 40);

        tfQuantity.setBackground(new java.awt.Color(51, 51, 51));
        tfQuantity.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfQuantity.setForeground(new java.awt.Color(255, 255, 255));
        tfQuantity.setText("Quantity");
        tfQuantity.setBorder(null);
        tfQuantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfQuantityMouseClicked(evt);
            }
        });
        tfQuantity.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfQuantityInputMethodTextChanged(evt);
            }
        });
        tfQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantityActionPerformed(evt);
            }
        });
        tfQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantityKeyTyped(evt);
            }
        });
        getContentPane().add(tfQuantity);
        tfQuantity.setBounds(360, 460, 210, 40);

        jlBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ManageSalesInvoice.png"))); // NOI18N
        getContentPane().add(jlBL);
        jlBL.setBounds(0, 0, 1280, 720);

        btnAdd.setText("jButton1");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(440, 572, 160, 40);

        btnUpdate.setText("jButton2");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(680, 570, 160, 40);

        btnRemove.setText("jButton1");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(930, 570, 160, 40);

        btnCancle.setText("jButton1");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancle);
        btnCancle.setBounds(200, 572, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCustomerIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCustomerIDMouseClicked
        tfCustomerID.setText(null);
    }//GEN-LAST:event_tfCustomerIDMouseClicked

    private void tfWatchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfWatchIDMouseClicked
        tfWatchID.setText(null);
    }//GEN-LAST:event_tfWatchIDMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        String InvoiceID = tfInvoiceID.getText();
        String CustomerID = tfCustomerID.getText();
        String WatchID = tfWatchID.getText();
        String UnitPrice = tfUnitPrice.getText();
        String Quantity = tfQuantity.getText();

        sob = scob.AddInvoice(InvoiceID, CustomerID, WatchID, UnitPrice, Quantity);
        boolean result = scob.AddtoDB(sob);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully added to the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "Adding to the databse unsuccessfull","Error",0 );
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        String InvoiceID = tfInvoiceID.getText();
        String CustomerID = tfCustomerID.getText();
        String WatchID = tfWatchID.getText();
        String UnitPrice = tfUnitPrice.getText();
        String Quantity = tfQuantity.getText();
        
        boolean result = scob.UpdateDB(InvoiceID, CustomerID, WatchID, UnitPrice, Quantity);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully updated the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "updating the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String InvoiceID = tfInvoiceID.getText();
        
        tfCustomerID.setText(null);
        tfWatchID.setText(null);
        tfQuantity.setText(null);
        tfUnitPrice.setText(null);
        
        boolean result = scob.DeleteDB(InvoiceID);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully deleted from the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "deleting from the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tfUnitPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUnitPriceMouseClicked
        tfUnitPrice.setText(null);
    }//GEN-LAST:event_tfUnitPriceMouseClicked

    private void tfInvoiceIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfInvoiceIDMouseClicked
        tfInvoiceID.setText(null);
    }//GEN-LAST:event_tfInvoiceIDMouseClicked

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancleActionPerformed

    private void tfQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantityKeyTyped

        
    }//GEN-LAST:event_tfQuantityKeyTyped

    private void tfQuantityInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfQuantityInputMethodTextChanged

    }//GEN-LAST:event_tfQuantityInputMethodTextChanged

    private void tfQuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfQuantityMouseClicked
        tfQuantity.setText(null);
    }//GEN-LAST:event_tfQuantityMouseClicked

    private void tfUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnitPriceActionPerformed

    private void tfQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSalesInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlBL;
    private javax.swing.JTextField tfCustomerID;
    private javax.swing.JTextField tfInvoiceID;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfUnitPrice;
    private javax.swing.JTextField tfWatchID;
    // End of variables declaration//GEN-END:variables
}
