/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.Supplier;
import Controller.SupplierController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.JFrame;

/**
 *
 * @author Pamud
 */
public class ManagePartSup extends javax.swing.JFrame {

    Supplier sob;
    SupplierController scob;
    
    public ManagePartSup() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        tfSupplierID.setBackground(new java.awt.Color(0,0,0,1));
        tfComopanyName.setBackground(new java.awt.Color(0,0,0,1));
        tfWatchID.setBackground(new java.awt.Color(0,0,0,1));
        tfPartID.setBackground(new java.awt.Color(0,0,0,1));
        
        scob = new SupplierController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfSupplierID = new javax.swing.JTextField();
        tfComopanyName = new javax.swing.JTextField();
        tfWatchID = new javax.swing.JTextField();
        tfPartID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Part Suppliers ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 40, 470, 60);

        tfSupplierID.setBackground(new java.awt.Color(51, 51, 51));
        tfSupplierID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfSupplierID.setForeground(new java.awt.Color(255, 255, 255));
        tfSupplierID.setText("Supplier ID");
        tfSupplierID.setBorder(null);
        tfSupplierID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSupplierIDMouseClicked(evt);
            }
        });
        tfSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSupplierIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfSupplierID);
        tfSupplierID.setBounds(400, 180, 430, 27);

        tfComopanyName.setBackground(new java.awt.Color(51, 51, 51));
        tfComopanyName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfComopanyName.setForeground(new java.awt.Color(255, 255, 255));
        tfComopanyName.setText("Company Name");
        tfComopanyName.setBorder(null);
        tfComopanyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfComopanyNameMouseClicked(evt);
            }
        });
        tfComopanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfComopanyNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfComopanyName);
        tfComopanyName.setBounds(400, 280, 430, 27);

        tfWatchID.setBackground(new java.awt.Color(51, 51, 51));
        tfWatchID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfWatchID.setForeground(new java.awt.Color(255, 255, 255));
        tfWatchID.setText("Watch ID");
        tfWatchID.setBorder(null);
        tfWatchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfWatchIDMouseClicked(evt);
            }
        });
        tfWatchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWatchIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfWatchID);
        tfWatchID.setBounds(400, 370, 430, 27);

        tfPartID.setBackground(new java.awt.Color(51, 51, 51));
        tfPartID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfPartID.setForeground(new java.awt.Color(255, 255, 255));
        tfPartID.setText("Part ID");
        tfPartID.setBorder(null);
        tfPartID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPartIDMouseClicked(evt);
            }
        });
        tfPartID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPartIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfPartID);
        tfPartID.setBounds(400, 450, 430, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Manage Part Suppliers.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        btnAdd.setText("jButton1");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(460, 562, 150, 50);

        btnUpdate.setText("jButton2");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(665, 562, 160, 50);

        btnRemove.setText("jButton3");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(875, 562, 150, 50);

        btnCancle.setText("jButton1");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancle);
        btnCancle.setBounds(250, 562, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfComopanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfComopanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComopanyNameActionPerformed

    private void tfWatchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWatchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWatchIDActionPerformed

    private void tfPartIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPartIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPartIDActionPerformed

    private void tfSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSupplierIDActionPerformed

    private void tfPartIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPartIDMouseClicked
        tfPartID.setText(null);
    }//GEN-LAST:event_tfPartIDMouseClicked

    private void tfSupplierIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSupplierIDMouseClicked
        tfSupplierID.setText(null);
    }//GEN-LAST:event_tfSupplierIDMouseClicked

    private void tfComopanyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComopanyNameMouseClicked
        tfComopanyName.setText(null);
    }//GEN-LAST:event_tfComopanyNameMouseClicked

    private void tfWatchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfWatchIDMouseClicked
        tfWatchID.setText(null);
    }//GEN-LAST:event_tfWatchIDMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String SupplierID = tfSupplierID.getText();
        String CompanyName = tfComopanyName.getText();
        String WatchID = tfWatchID.getText();
        String PartID = tfPartID.getText();

        sob = scob.AddSupplier(SupplierID, CompanyName, WatchID, PartID);
        boolean result = scob.AddtoDB(sob);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully added to the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "Adding to the databse unsuccessfull","Error",0 );
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String SupplierID = tfSupplierID.getText();
        String CompanyName = tfComopanyName.getText();
        String WatchID = tfWatchID.getText();
        String PartID = tfPartID.getText();
        
        boolean result = scob.UpdateDB(SupplierID, CompanyName, WatchID, PartID);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully updated the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "updating the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String SupplierID = tfSupplierID.getText();
        
        tfComopanyName.setText(null);
        tfComopanyName.setText(null);
        tfWatchID.setText(null);
        tfPartID.setText(null);
        
        boolean result = scob.DeleteDB(SupplierID);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully deleted from the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "deleting from the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        Dashboard l1 = new Dashboard();
        l1.show();
        dispose();
    }//GEN-LAST:event_btnCancleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePartSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePartSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePartSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePartSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePartSup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfComopanyName;
    private javax.swing.JTextField tfPartID;
    private javax.swing.JTextField tfSupplierID;
    private javax.swing.JTextField tfWatchID;
    // End of variables declaration//GEN-END:variables
}
