/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;
    import Model.Watch;
    import Controller.WatchController;
    import javax.swing.JFrame;
    import javax.swing.JOptionPane;

import javax.swing.JFrame;

/**
 *
 * @author Pamud
 */
public class ManageWatch extends javax.swing.JFrame {

    Model.Watch wob;
    WatchController wcob;
    
    public ManageWatch() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tfWatchID.setBackground(new java.awt.Color(0,0,0,1));
        tfBrand.setBackground(new java.awt.Color(0,0,0,1));
        tfMaterial.setBackground(new java.awt.Color(0,0,0,1));
        tfUnitPrice.setBackground(new java.awt.Color(0,0,0,1));
        
        wcob = new WatchController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfBrand = new javax.swing.JTextField();
        tfWatchID = new javax.swing.JTextField();
        tfMaterial = new javax.swing.JTextField();
        tfUnitPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Watch");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 40, 220, 50);

        tfBrand.setBackground(new java.awt.Color(67, 16, 16));
        tfBrand.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfBrand.setForeground(new java.awt.Color(255, 255, 255));
        tfBrand.setText("Brand Name");
        tfBrand.setBorder(null);
        tfBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfBrandMouseClicked(evt);
            }
        });
        getContentPane().add(tfBrand);
        tfBrand.setBounds(350, 250, 530, 30);

        tfWatchID.setBackground(new java.awt.Color(67, 16, 16));
        tfWatchID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfWatchID.setForeground(new java.awt.Color(255, 255, 255));
        tfWatchID.setText("Watch ID");
        tfWatchID.setBorder(null);
        tfWatchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfWatchIDMouseClicked(evt);
            }
        });
        tfWatchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWatchIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfWatchID);
        tfWatchID.setBounds(350, 160, 530, 30);

        tfMaterial.setBackground(new java.awt.Color(67, 16, 16));
        tfMaterial.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfMaterial.setForeground(new java.awt.Color(255, 255, 255));
        tfMaterial.setText("Material");
        tfMaterial.setBorder(null);
        tfMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfMaterialMouseClicked(evt);
            }
        });
        getContentPane().add(tfMaterial);
        tfMaterial.setBounds(350, 340, 530, 30);

        tfUnitPrice.setBackground(new java.awt.Color(67, 16, 16));
        tfUnitPrice.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfUnitPrice.setForeground(new java.awt.Color(255, 255, 255));
        tfUnitPrice.setText("Unit Price");
        tfUnitPrice.setBorder(null);
        tfUnitPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUnitPriceMouseClicked(evt);
            }
        });
        getContentPane().add(tfUnitPrice);
        tfUnitPrice.setBounds(350, 430, 530, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Watch.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1310, 740);

        btnAdd.setText("jButton1");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(440, 572, 160, 30);

        btnUpdate.setText("jButton2");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(685, 572, 160, 30);

        btnRemove.setText("jButton3");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(925, 570, 160, 40);

        btnCancle.setText("jButton1");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancle);
        btnCancle.setBounds(190, 572, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBrandMouseClicked
        tfBrand.setText(null);
    }//GEN-LAST:event_tfBrandMouseClicked

    private void tfWatchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfWatchIDMouseClicked
        tfWatchID.setText(null);
    }//GEN-LAST:event_tfWatchIDMouseClicked

    private void tfWatchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWatchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWatchIDActionPerformed

    private void tfMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfMaterialMouseClicked
        tfMaterial.setText(null);
    }//GEN-LAST:event_tfMaterialMouseClicked

    private void tfUnitPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUnitPriceMouseClicked
        tfUnitPrice.setText(null);
    }//GEN-LAST:event_tfUnitPriceMouseClicked

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String WatchID = tfWatchID.getText();
        String BrandName = tfBrand.getText();
        String Material = tfMaterial.getText();
        String UntiPrice = tfUnitPrice.getText();

        wob = wcob.AddWatch(WatchID, BrandName, UntiPrice, UntiPrice);
        boolean result = wcob.AddtoDB(wob);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully added to the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "Adding to the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String WatchID = tfWatchID.getText();
        String BrandName = tfBrand.getText();
        String Material = tfMaterial.getText();
        String UntiPrice = tfUnitPrice.getText();
        
        boolean result = wcob.UpdateDB(WatchID, BrandName, Material, UntiPrice);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully updated the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "updating the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String WatchID = tfWatchID.getText();
        
        tfMaterial.setText(null);
        tfUnitPrice.setText(null);
        tfBrand.setText(null);
        
        boolean result = wcob.DeleteDB(WatchID);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully deleted from the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "deleting from the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Model.Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Model.Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Model.Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Model.Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageWatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfMaterial;
    private javax.swing.JTextField tfUnitPrice;
    private javax.swing.JTextField tfWatchID;
    // End of variables declaration//GEN-END:variables
}
