/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.CustomerController;
import Model.Customer;  
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pamud
 */
public class RegNewCustomer extends javax.swing.JFrame {

 Customer cob;
 CustomerController ccob;
 
         
         
         
    public RegNewCustomer() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tfName.setBackground(new java.awt.Color(0,0,0,1));
        tfAdress.setBackground(new java.awt.Color(0,0,0,1));
        tfEmail.setBackground(new java.awt.Color(0,0,0,1));
        tfPhone.setBackground(new java.awt.Color(0,0,0,1));
        ccob = new CustomerController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfName = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancle = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfName.setBackground(new java.awt.Color(67, 16, 16));
        tfName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setText("Customer Name");
        tfName.setBorder(null);
        tfName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNameMouseClicked(evt);
            }
        });
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName);
        tfName.setBounds(290, 200, 530, 30);

        tfAdress.setBackground(new java.awt.Color(67, 16, 16));
        tfAdress.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfAdress.setForeground(new java.awt.Color(255, 255, 255));
        tfAdress.setText("Address");
        tfAdress.setBorder(null);
        tfAdress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfAdressMouseClicked(evt);
            }
        });
        getContentPane().add(tfAdress);
        tfAdress.setBounds(290, 290, 530, 30);

        tfEmail.setBackground(new java.awt.Color(67, 16, 16));
        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        tfEmail.setText("Email");
        tfEmail.setBorder(null);
        tfEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEmailMouseClicked(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(290, 380, 530, 30);

        tfPhone.setBackground(new java.awt.Color(67, 16, 16));
        tfPhone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfPhone.setForeground(new java.awt.Color(255, 255, 255));
        tfPhone.setText("Phone Number");
        tfPhone.setBorder(null);
        tfPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPhoneMouseClicked(evt);
            }
        });
        getContentPane().add(tfPhone);
        tfPhone.setBounds(290, 470, 530, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/RegNewCustomer.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        btnCancle.setText("jButton1");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancle);
        btnCancle.setBounds(180, 602, 160, 40);

        btnAdd.setText("jButton2");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(430, 602, 160, 40);

        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(682, 602, 150, 30);

        btnRemove.setText("remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(920, 602, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed


        String name = tfName.getText();
        String Adress = tfAdress.getText();
        String Email = tfEmail.getText();
        String phone =  tfPhone.getText(); 
        String cusID = name.substring(0,2);
        cusID = cusID.concat(phone.substring(3,6));
        cob = ccob.AddCustomer(cusID, name, Adress, Email, phone);
        boolean result = ccob.AddtoDB(cob);
        JOptionPane.showMessageDialog(rootPane, "Successfully added to the database","info",1 );
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully added to the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "Successfully added to the database","info",1  );
        }
        
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void tfNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNameMouseClicked
        tfName.setText(null);
    }//GEN-LAST:event_tfNameMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String name = tfName.getText();
        String Adress = tfAdress.getText();
        String Email = tfEmail.getText();
        String phone =  tfPhone.getText(); 
        boolean result = ccob.UpdateDB(name, Adress, Email, phone);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully updated the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "updating the databse unsuccessfull","Error",0 );
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfAdressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAdressMouseClicked
        tfAdress.setText(null);
    }//GEN-LAST:event_tfAdressMouseClicked

    private void tfEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEmailMouseClicked
        tfEmail.setText(null);
    }//GEN-LAST:event_tfEmailMouseClicked

    private void tfPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPhoneMouseClicked
        tfPhone.setText(null);
    }//GEN-LAST:event_tfPhoneMouseClicked

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
       
         new Dashboard().setVisible(true);
         dispose();
        
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String name = tfName.getText();
        String Adress = tfAdress.getText();
        boolean result = ccob.DeleteDB(name, Adress);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Successfully deleted from the database","info",1 );
        }else{
            JOptionPane.showMessageDialog(rootPane, "deleting from the databse unsuccessfull","Error",0 );
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegNewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPhone;
    // End of variables declaration//GEN-END:variables
}
